services:
  #########################################################################
  # Regtest mining                                                        #
  #########################################################################
  miner:
    image: initialised-demo
    container_name: miner
    depends_on:
      - node1
      - orchestrator
      - node-explorer
      - dashboard
    command:
      - bash
      - -c
      - |
        until curl -s --user bitcoin:bitcoin --data-binary '{"jsonrpc":"1.0","id":"curltest","method":"getwalletinfo"}' -H 'content-type: text/plain;' http://node1:18332 | grep -q '"error":null'; do
          sleep 1
        done
        RESP=$(curl -s --user bitcoin:bitcoin --data-binary '{"jsonrpc":"1.0","id":"curltest","method":"getnewaddress"}' -H 'content-type: text/plain;' http://node1:18332)
        ADDRESS=$(echo "$$RESP" | sed -n 's/.*"result":[[:space:]]*"\([^"]*\)".*/\1/p')
        echo "Bitcoin address: $$ADDRESS"
        RESPONSE=$(curl -s --user bitcoin:bitcoin --data-binary "{\"jsonrpc\":\"1.0\",\"id\":\"curltest\",\"method\":\"generatetoaddress\",\"params\":[100,\"$$ADDRESS\"]}" -H 'content-type: text/plain;' http://node1:18332)
        echo "Mining complete"
    networks:
      - regtest_network

  #########################################################################
  # SUI node                                                              #
  #########################################################################
  sui-node:
    image: custom-sui
    container_name: sui-node
    command: >
      bash -c "
        RUST_LOG=off,sui_node=info sui start --with-faucet --force-regenesis > sui.log 2>&1 &
        sleep 2;
        expect -c \"spawn sui client new-env --alias local --rpc http://0.0.0.0:9000; \
          sleep 1; \
          send \\\"y\\\\r\\\"; \
          sleep 0.2; \
          send \\\"\\\\r\\\"; \
          sleep 0.2; \
          send \\\"0\\\\r\\\"; \
          expect eof\"; \
        sui client switch --env local; \
        sui client active-address; \
        sui client faucet; \
        sui-explorer-local start > explorer.log 2>&1 & \
        sleep infinity
      "
    ports:
      - "9000:9000"
      - "9184:9184"
      - "8081:8080"

  #########################################################################
  # ETH node                                                              #
  #########################################################################
  eth-node:
    image: custom-eth
    container_name: eth-node
    working_dir: /app/evm
    command: >
      bash -c "
        npx hardhat node
        sleep infinity
      "
    ports:
      - "8545:8545"


# volumes:
#   sui-data:
#   hardhat-cache:
#   hardhat-artifacts:
