FROM mysten/sui-tools:devnet

# Install only what’s necessary
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bash \
        curl \
        tini \
        expect \
        nodejs \
        npm && \
    rm -rf /var/lib/apt/lists/*

# Install Sui explorer globally
RUN npm install -g sui-explorer-local@latest && \
    npm cache clean --force

# Entrypoint
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["bash"]
