services:
  #########################################################################
  # Regtest mining                                                        #
  #########################################################################
  miner:
    image: init-demo
    container_name: miner
    depends_on:
      - node1
      - orchestrator
      - node-explorer
      - dashboard
    command:
      - bash
      - -c
      - |
        until curl -s --user bitcoin:bitcoin --data-binary '{"jsonrpc":"1.0","id":"curltest","method":"getwalletinfo"}' -H 'content-type: text/plain;' http://node1:18332 | grep -q '"error":null'; do
          sleep 1
        done
        RESP=$(curl -s --user bitcoin:bitcoin --data-binary '{"jsonrpc":"1.0","id":"curltest","method":"getnewaddress"}' -H 'content-type: text/plain;' http://node1:18332)
        ADDRESS=$(echo "$$RESP" | sed -n 's/.*"result":[[:space:]]*"\([^"]*\)".*/\1/p')
        echo "Bitcoin address: $$ADDRESS"
        RESPONSE=$(curl -s --user bitcoin:bitcoin --data-binary "{\"jsonrpc\":\"1.0\",\"id\":\"curltest\",\"method\":\"generatetoaddress\",\"params\":[100,\"$$ADDRESS\"]}" -H 'content-type: text/plain;' http://node1:18332)
        echo "Mining complete"
        sleep infinity
    networks:
      - regtest_network

  #########################################################################
  # ETH node                                                              #
  #########################################################################
  eth-node:
    image: custom-eth
    container_name: eth-node
    working_dir: /app/evm
    command: >
      bash -c "
        npx hardhat node
        sleep infinity
      "
    ports:
      - "8545:8545"
    networks:
      - regtest_network

  #########################################################################
  # ETH demo                                                              #
  #########################################################################
  eth-demo:
    image: init-demo
    container_name: eth-demo
    depends_on:
      - eth-node
      - miner
      - node1
    working_dir: /app
    command:
      - bash
      - -c
      - |
        sed -i 's/127.0.0.1/eth-node/g' ./evm/hardhat.config.ts
        sed -i 's/localhost/node1/g' ./cli/bsv_config.toml
        cd cli
        python3 -m evm_demo setup
        python3 -m evm_demo pegin --user alice --pegin-amount 10 --network regtest
        python3 -m evm_demo transfer --sender alice --receiver bob --token-index 0 --network regtest
        python3 -m evm_demo burn --user bob --token-index 0 --network regtest
        python3 -m evm_demo pegout
        echo "Demo complete"
        sleep infinity
    networks:
      - regtest_network


      # - bash
      # - -c
      # - |
      #   sed -i 's/127.0.0.1/eth-node/g' ./evm/hardhat.config.ts
      #   sed -i 's/localhost/node1/g' ./cli/bsv_config.toml
      #   sed -i 's/    conditional_generate_block(wallet_manager.network)/    wallet_manager=WalletManager.load_wallet("./eth_bsv_wallet.json", interface_factory.set_config(load_config("bsv_config.toml")["bsv_client"]))\
      #       conditional_generate_block(wallet_manager.network)/g' ./cli/evm_demo.py
      #   sed -i 's/    wallet_manager.generate_pegout(user, issuer_index, -1)/    pegout, change, funding_tx, funding_index = wallet_manager._generate_pegout(user, issuer_index, -1)\
      #       wallet_manager=WalletManager.load_wallet("./eth_bsv_wallet.json", interface_factory.set_config(load_config("bsv_config.toml")["bsv_client"]))\
      #       wallet_manager._spend_pegout(pegout, change, funding_tx, funding_index, issuer_index, user)/g' ./cli/evm_demo.py
      #   sed -i 's/    wallet_manager.burn_token(user, token_index)/    proof, input_val = wallet_manager._burn_step_1(user, token_index)\
      #       wallet_manager.save_wallet("./eth_bsv_wallet.json")\
      #       wallet_manager=WalletManager.load_wallet("./eth_bsv_wallet.json", interface_factory.set_config(load_config("bsv_config.toml")["bsv_client"]))\
      #       spending_tx, token_tx, token_tx_index, pegout_tx, pegout_tx_index, funding_tx, funding_tx_index = wallet_manager._burn_step_2(user, token_index)\
      #       wallet_manager.save_wallet("./eth_bsv_wallet.json")\
      #       wallet_manager=WalletManager.load_wallet("./eth_bsv_wallet.json", interface_factory.set_config(load_config("bsv_config.toml")["bsv_client"]))\
      #       spending_tx = wallet_manager._burn_step_3(user, token_index, proof, input_val, spending_tx, token_tx, token_tx_index, pegout_tx, pegout_tx_index, funding_tx, funding_tx_index)\
      #       wallet_manager.save_wallet("./eth_bsv_wallet.json")\
      #       wallet_manager=WalletManager.load_wallet("./eth_bsv_wallet.json", interface_factory.set_config(load_config("bsv_config.toml")["bsv_client"]))\
      #       wallet_manager._burn_step_4(user, token_index, spending_tx)/g' ./cli/evm_demo.py
      #   cd cli
      #   python3 -m evm_demo setup
      #   python3 -m evm_demo pegin --user alice --pegin-amount 10 --network regtest
      #   python3 -m evm_demo transfer --sender alice --receiver bob --token-index 0 --network regtest
      #   python3 -m evm_demo burn --user bob --token-index 0 --network regtest
      #   python3 -m evm_demo pegout
