@startuml
title Sui Bridge
left to right direction

actor User as U

actor Admin as A

cloud Sui
cloud BSV


package "Bridge System" {

    (Transfer Sui -> BSV) 
    (Transfer BSV -> Sui)
    
    (Upload Bridge Smart Contract) ..> Sui
    (Upload Oracle Smart Contract) ..> Sui

    (Setup ZKEngine)

}



U --> (Transfer Sui -> BSV)
U --> (Transfer BSV -> Sui)

(Transfer Sui -> BSV) ..> BSV
(Transfer BSV -> Sui) ..> BSV

(Transfer Sui -> BSV) ..> Sui
(Transfer BSV -> Sui) ..> Sui


A --> (Upload Bridge Smart Contract)
A --> (Upload Oracle Smart Contract)
A --> (Setup ZKEngine)



@enduml